"""Add GitHub entity tables

Revision ID: 057d8048eb0f
Revises: 
Create Date: 2026-03-15 15:34:21.908378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057d8048eb0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_github_id'), 'repos', ['github_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('github_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_table('ci_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('head_sha', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_runs_conclusion'), 'ci_runs', ['conclusion'], unique=False)
    op.create_index(op.f('ix_ci_runs_github_id'), 'ci_runs', ['github_id'], unique=True)
    op.create_index(op.f('ix_ci_runs_head_sha'), 'ci_runs', ['head_sha'], unique=False)
    op.create_index(op.f('ix_ci_runs_repo_id'), 'ci_runs', ['repo_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('oid', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('committed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_author_email'), 'commits', ['author_email'], unique=False)
    op.create_index(op.f('ix_commits_author_login'), 'commits', ['author_login'], unique=False)
    op.create_index(op.f('ix_commits_committed_date'), 'commits', ['committed_date'], unique=False)
    op.create_index(op.f('ix_commits_oid'), 'commits', ['oid'], unique=False)
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_github_id'), 'issues', ['github_id'], unique=True)
    op.create_index(op.f('ix_issues_number'), 'issues', ['number'], unique=False)
    op.create_index(op.f('ix_issues_repo_id'), 'issues', ['repo_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_risk_score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_author_login'), 'pull_requests', ['author_login'], unique=False)
    op.create_index(op.f('ix_pull_requests_github_id'), 'pull_requests', ['github_id'], unique=True)
    op.create_index(op.f('ix_pull_requests_number'), 'pull_requests', ['number'], unique=False)
    op.create_index(op.f('ix_pull_requests_repo_id'), 'pull_requests', ['repo_id'], unique=False)
    op.create_table('user_repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_pr_comments_author_login'), 'pr_comments', ['author_login'], unique=False)
    op.create_index(op.f('ix_pr_comments_pr_id'), 'pr_comments', ['pr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_comments_pr_id'), table_name='pr_comments')
    op.drop_index(op.f('ix_pr_comments_author_login'), table_name='pr_comments')
    op.drop_table('pr_comments')
    op.drop_table('user_repos')
    op.drop_index(op.f('ix_pull_requests_repo_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_login'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_issues_repo_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_number'), table_name='issues')
    op.drop_index(op.f('ix_issues_github_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_oid'), table_name='commits')
    op.drop_index(op.f('ix_commits_committed_date'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_login'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_email'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_ci_runs_repo_id'), table_name='ci_runs')
    op.drop_index(op.f('ix_ci_runs_head_sha'), table_name='ci_runs')
    op.drop_index(op.f('ix_ci_runs_github_id'), table_name='ci_runs')
    op.drop_index(op.f('ix_ci_runs_conclusion'), table_name='ci_runs')
    op.drop_table('ci_runs')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repos_github_id'), table_name='repos')
    op.drop_table('repos')
    # ### end Alembic commands ###
