"""add_arch_analysis

Revision ID: 2f0e5a54fbcd
Revises: 057d8048eb0f
Create Date: 2026-03-17 11:20:17.034845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0e5a54fbcd'
down_revision: Union[str, Sequence[str], None] = '057d8048eb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arch_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('import_cycles', sa.JSON(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arch_analysis_repo_id'), 'arch_analysis', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arch_analysis_repo_id'), table_name='arch_analysis')
    op.drop_table('arch_analysis')
    # ### end Alembic commands ###
