"""commit_oid_unique

Revision ID: 75bfb673ce4f
Revises: 2f0e5a54fbcd
Create Date: 2026-03-17 11:36:57.433415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bfb673ce4f'
down_revision: Union[str, Sequence[str], None] = '2f0e5a54fbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commits', ['repo_id', 'oid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='unique')
    # ### end Alembic commands ###
