/**
 * RepoLens GitHub Bot
 *
 * Listens for pull_request.opened / synchronize webhooks,
 * fetches risk analysis from the RepoLens API, and posts:
 *  - A structured PR comment with the risk breakdown
 *  - A GitHub Check Run (passes / fails based on threshold)
 *
 * Required env vars:
 *   GITHUB_APP_ID          — GitHub App ID
 *   GITHUB_PRIVATE_KEY     — PEM private key (newlines as \n)
 *   GITHUB_WEBHOOK_SECRET  — webhook secret for HMAC validation
 *   REPOLENS_API_URL       — e.g. http://api:8000
 *   REPOLENS_API_KEY       — shared secret for internal API calls
 *   PORT                   — (optional) defaults to 3000
 */

const express = require('express');
const crypto  = require('crypto');
const axios   = require('axios');
const dotenv  = require('dotenv');

dotenv.config();

// ── Octokit ────────────────────────────────────────────────────────────────
let Octokit, createAppAuth;
try {
  ({ Octokit } = require('@octokit/rest'));
  ({ createAppAuth } = require('@octokit/auth-app'));
} catch (e) {
  console.warn('[bot] @octokit packages not installed — run npm install inside bot/');
}

const app  = express();
const PORT = process.env.PORT || 3000;

const REPOLENS_API = (process.env.REPOLENS_API_URL || 'http://api:8000').replace(/\/$/, '');
const API_KEY      = process.env.REPOLENS_API_KEY || 'internal_key';
const WEBHOOK_SECRET = process.env.GITHUB_WEBHOOK_SECRET || '';

// Default risk threshold — overridden per-repo by config.block_threshold from the API
const DEFAULT_CRITICAL_THRESHOLD = 75;

// ── Webhook signature verification ─────────────────────────────────────────
function verifySignature(req, rawBody) {
  if (!WEBHOOK_SECRET) return true; // skip in dev
  const sig = req.headers['x-hub-signature-256'];
  if (!sig) return false;
  const expected = 'sha256=' + crypto.createHmac('sha256', WEBHOOK_SECRET).update(rawBody).digest('hex');
  return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected));
}

// ── GitHub App authentication ───────────────────────────────────────────────
function buildOctokit(installationId) {
  if (!Octokit || !createAppAuth) return null;

  const privateKey = (process.env.GITHUB_PRIVATE_KEY || '').replace(/\\n/g, '\n');
  const appId      = process.env.GITHUB_APP_ID;

  if (!appId || !privateKey) {
    console.warn('[bot] GITHUB_APP_ID / GITHUB_PRIVATE_KEY not set — using unauthenticated Octokit');
    return new Octokit();
  }

  return new Octokit({
    authStrategy: createAppAuth,
    auth: { appId, privateKey, installationId },
  });
}

// ── RepoLens API helpers ────────────────────────────────────────────────────
async function getRepoLensRepo(owner, repoName) {
  try {
    const res = await axios.get(`${REPOLENS_API}/internal/repos/lookup`, {
      params: { owner, name: repoName },
      headers: { 'X-Internal-Key': API_KEY },
      timeout: 10_000,
    });
    return res.data;
  } catch (e) {
    console.error('[bot] getRepoLensRepo failed:', e.message);
    return null;
  }
}

async function getRisk(repoId) {
  try {
    const res = await axios.get(`${REPOLENS_API}/internal/repos/${repoId}/analysis`, {
      headers: { 'X-Internal-Key': API_KEY },
      timeout: 30_000,
    });
    return res.data;
  } catch (e) {
    console.error('[bot] getRisk failed:', e.message);
    return null;
  }
}

// ── Comment formatting ──────────────────────────────────────────────────────
function riskEmoji(score) {
  if (score >= 75) return '🔴';
  if (score >= 55) return '🟠';
  if (score >= 30) return '🟡';
  return '🟢';
}

function ratingBadge(rating) {
  const map = { elite: '🏆 Elite', high: '✅ High', medium: '⚠️ Medium', low: '🔴 Low', unknown: '❓ N/A' };
  return map[rating] || rating;
}

function formatComment(risk, explanation, owner, repoName, prNumber) {
  const score   = risk.score ?? 0;
  const bd      = risk.breakdown ?? {};
  const label   = (risk.label ?? 'unknown').toUpperCase();
  const summary = explanation?.summary ?? '_No explanation available._';
  const actions = explanation?.actions ?? [];

  const breakdownRows = Object.entries(bd).map(([k, v]) => `| ${k.replace(/_/g, ' ')} | ${v}/100 |`).join('\n');

  const actionLines = actions.length
    ? actions.map(a => `- **${a.type}**${a.file ? ` \`${a.file}\`` : ''}: ${a.description}`).join('\n')
    : '_No specific actions recommended._';

  return `## ${riskEmoji(score)} RepoLens Risk Analysis — ${label} (${score}/100)

${summary}

### Score Breakdown
| Signal | Score |
|--------|-------|
${breakdownRows}

### Recommended Actions
${actionLines}

---
<details>
<summary>About this analysis</summary>

This comment was generated by [RepoLens](${REPOLENS_API}) analysing coupling, architecture, bus factor, CI flakiness, and team collaboration signals from your repository history.

_Risk thresholds: 🟢 Low (0–30) · 🟡 Medium (31–55) · 🟠 High (56–75) · 🔴 Critical (76–100)_
</details>`;
}

// ── Webhook handler ─────────────────────────────────────────────────────────
app.post('/webhook', express.raw({ type: '*/*' }), async (req, res) => {
  const rawBody = req.body;

  if (!verifySignature(req, rawBody)) {
    return res.status(401).send('Invalid signature');
  }

  let payload;
  try {
    payload = JSON.parse(rawBody.toString('utf8'));
  } catch {
    return res.status(400).send('Invalid JSON');
  }

  const event = req.headers['x-github-event'];
  res.status(202).send('Accepted'); // Respond immediately — process async

  if (event !== 'pull_request') return;
  const action = payload.action;
  if (!['opened', 'synchronize', 'reopened'].includes(action)) return;

  const pr           = payload.pull_request;
  const owner        = payload.repository.owner.login;
  const repoName     = payload.repository.name;
  const installId    = payload.installation?.id;
  const headSha      = pr.head.sha;
  const prNumber     = pr.number;

  console.log(`[bot] PR #${prNumber} ${action} in ${owner}/${repoName}`);

  const octokit = buildOctokit(installId);
  if (!octokit) {
    console.warn('[bot] No Octokit — skipping comment/check run');
    return;
  }

  // Create a pending check run immediately
  let checkRunId;
  try {
    const cr = await octokit.checks.create({
      owner, repo: repoName, name: 'RepoLens Risk Analysis',
      head_sha: headSha, status: 'in_progress',
      output: { title: 'Analysing…', summary: 'RepoLens is computing the risk score for this PR.' },
    });
    checkRunId = cr.data.id;
  } catch (e) {
    console.error('[bot] Could not create check run:', e.message);
  }

  // Fetch risk from RepoLens
  const repolensRepo = await getRepoLensRepo(owner, repoName);
  let risk, explanation;

  let violations = [];
  let botConfig  = { block_threshold: DEFAULT_CRITICAL_THRESHOLD, warn_only: false };

  if (repolensRepo) {
    const analysis = await getRisk(repolensRepo.id);
    risk        = analysis?.risk        ?? { score: 0, label: 'unknown', breakdown: {} };
    explanation = analysis?.explanation ?? null;
    violations  = analysis?.violations  ?? [];
    if (analysis?.config) {
      botConfig.block_threshold = analysis.config.block_threshold ?? DEFAULT_CRITICAL_THRESHOLD;
      botConfig.warn_only       = analysis.config.warn_only       ?? false;
    }
  } else {
    console.warn(`[bot] ${owner}/${repoName} not connected to RepoLens`);
    risk        = { score: 0, label: 'unknown', breakdown: {} };
    explanation = { summary: 'This repository is not yet connected to RepoLens.' };
  }

  const commentBody = formatComment(risk, explanation, owner, repoName, prNumber);

  // Post PR body comment
  try {
    await octokit.issues.createComment({ owner, repo: repoName, issue_number: prNumber, body: commentBody });
    console.log(`[bot] Comment posted on PR #${prNumber}`);
  } catch (e) {
    console.error('[bot] Could not post comment:', e.message);
  }

  // Post inline diff annotations for architectural violations
  if (violations.length > 0) {
    try {
      // Get the files changed in this PR
      const filesRes = await octokit.pulls.listFiles({ owner, repo: repoName, pull_number: prNumber });
      const changedFiles = new Set(filesRes.data.map(f => f.filename));

      const reviewComments = violations
        .filter(v => {
          const filePath = v.file || v.source_file || '';
          return changedFiles.has(filePath) && (v.line || v.line_number) > 0;
        })
        .map(v => ({
          path: v.file || v.source_file,
          line: v.line || v.line_number || 1,
          side: 'RIGHT',
          body: `**[RepoLens] ${v.type || 'Arch Violation'}** *(${v.severity || 'warning'})*: ${v.description || v.message || 'Layer boundary violation detected.'}`,
        }));

      if (reviewComments.length > 0) {
        await octokit.pulls.createReview({
          owner, repo: repoName, pull_number: prNumber,
          commit_id: headSha,
          event: 'COMMENT',
          comments: reviewComments,
        });
        console.log(`[bot] Posted ${reviewComments.length} inline annotation(s) on PR #${prNumber}`);
      }
    } catch (e) {
      // Inline annotations can fail if line numbers are outside the diff — log and continue
      console.warn('[bot] Could not post inline annotations:', e.message);
    }
  }

  // Update check run — respect per-repo warn_only config
  if (checkRunId) {
    try {
      const score = risk.score ?? 0;
      const exceedsThreshold = score >= botConfig.block_threshold;
      const conclusion = (exceedsThreshold && !botConfig.warn_only) ? 'failure' : 'success';
      await octokit.checks.update({
        owner, repo: repoName, check_run_id: checkRunId,
        status: 'completed', conclusion,
        output: {
          title: `Risk Score: ${score}/100 — ${(risk.label ?? 'unknown').toUpperCase()}`,
          summary: explanation?.summary ?? '',
          text: commentBody,
        },
      });
      console.log(`[bot] Check run updated: ${conclusion} (threshold=${botConfig.block_threshold}, warn_only=${botConfig.warn_only})`);
    } catch (e) {
      console.error('[bot] Could not update check run:', e.message);
    }
  }
});

// ── Health ──────────────────────────────────────────────────────────────────
app.get('/', (_req, res) => res.json({ status: 'ok', service: 'repolens-bot' }));

app.listen(PORT, () => console.log(`[bot] Listening on port ${PORT}`));
